### ISSUE TITLE
Tool showing incorrect recommendation to convert 9.png images to webp

### ISSUE THREAD

**Issue by garg-ketki** [android/size-analyzer#12]
The `./size-analyzer check-bundle <>.aab` is recommending to convert the images to webp. But on fetching the details of what all images can be converted to webp, it's showing a suggestion for 9-patch images as well. But as per [android documentation](https://developer.android.com/studio/write/convert-webp),  9-patch files cannot be converted to WebP images.

**Logs**
```
Convert base/res/drawable-xxhdpi-v4/tooltip_dark_bottom_right.9.png to webp with lossless encoding (saves 5.4 kiB)
Convert base/res/drawable-mdpi-v4/del_pattern.9.png to webp with lossless encoding (saves 8.1 kiB)
```
**Expected behavior**
Tool shouldn't recommend converting 9-patch images to webp. 

**Additional context**
What is the general practice to work with 9.png images? Should these be converted to vector drawables to reduce the size?

**Comment by tdeck** [comment]
This has been fixed in release 0.4.0.

I'm sorry it's taken so long to address this issue. The Size Analyzer was something of an experimental project, and we haven't had a team dedicated to continuing its development. Since I'm leaving Google in a couple of days, I thought I'd try to tie up these loose ends. I've also updated the README to reflect the status of the project.
