### ISSUE TITLE
Report is wrong about inaccessible files

### ISSUE THREAD

**Issue by tir38** [android/size-analyzer#6]
**Describe the bug**
Report is recommending I remove some files that are either obviously needed (like jniLibs), or not bound for the apk anyways (like buildSrc and .DS_Store files)

```
Remove inaccessible files
File app/src/main/.DS_Store does not appear to be a needed file.
File buildSrc/src/main/kotlin/io/XXXXandroid/gradle/TestDependencies.kt does not appear to be a needed file.
File buildSrc/src/main/kotlin/io/XXXX/android/gradle/XXXXPlugin.kt does not appear to be a needed file.
File xxx/src/main/.DS_Store does not appear to be a needed file.
File xxx/src/main/graphql/.DS_Store does not appear to be a needed file.
File xxx/src/main/graphql/com/.DS_Store does not appear to be a needed file.
File xxx/src/main/jniLibs/armeabi-v7a/libopus_jni.so does not appear to be a needed file.
```

**Size-Analyzer version(s) affected**
Version: 0.3.1

**Comment by tdeck** [comment]
This has been fixed in release 0.4.0. I have excluded these categories of files, although I suspect there are more types of files that we may wrongly report as suspect.

I'm sorry it's taken so long to address this issue. The Size Analyzer was something of an experimental project, and we haven't had a team dedicated to continuing its development. Since I'm leaving Google in a couple of days, I thought I'd try to tie up these loose ends. I've also updated the README to reflect the status of the project.
